name: Create Branch on Dispatch

on:
  repository_dispatch:
    types: [create-branch]

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create new branch
        run: |
          BRANCH_NAME="${{ github.event.client_payload.branch_name }}"
          echo "Creating branch: $BRANCH_NAME"
          git fetch origin
          DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
          git checkout -b "$BRANCH_NAME" "origin/$DEFAULT_BRANCH"
          git push origin "$BRANCH_NAME"